---
apiVersion: v2
type: application
name: db-operator
version: 1.15.0
# ---------------------------------------------------------------------------------
# -- All supported k8s versions are in the test:
# --  https://github.com/db-operator/charts/blob/main/.github/workflows/test.yaml
# ---------------------------------------------------------------------------------
kubeVersion: ">= 1.22-prerelease"
appVersion: "2.0.0"
description: The DB Operator creates databases and make them available in the cluster via Custom Resource.
home: https://github.com/db-operator/db-operator

maintainers:
  - name: Nikolai Rodionov
    email: allanger@zohomail.com
    url: https://badhouseplants.net

sources:
  - https://github.com/db-operator/db-operator
  - https://github.com/db-operator/cloudish-sql
  - https://github.com/db-operator/pgdump-gcs
  - https://github.com/db-operator/mydump-gcs
keywords:
  - database
  - Operator
  - mysql
  - postgres
