values: |
  webhook:
    install: true
    certificate:
      issuer:
        create: false
files:
  - Certificate-db-operator-webhook.yml
  - ConfigMap-db-operator-config.yml
  - Deployment-db-operator.yml
  - Deployment-db-operator-webhook.yml
  - ServiceAccount-db-operator.yml
  - ServiceAccount-db-operator-webhook.yml
  - ClusterRoleBinding-db-operator.yml
  - CustomResourceDefinition-databases.kinda.rocks
  - Service-db-operator-webhook.yml
  - ClusterRole-db-operator.yml
  - CustomResourceDefinition-dbusers.kinda.rocks
  - CustomResourceDefinition-dbinstances.kinda.rocks
  - MutatingWebhookConfiguration-db-operator-mutating-webhook-configuration.yml
  - ValidatingWebhookConfiguration-db-operator-validating-webhook-configuration.yml
